### PR TITLE
Transifex configuration

### PR DESCRIPTION
**Pull request by DavidePrincipi**
Added Transifex config file for the `tx` client.

Just remember to execute `tx push -s` when the source "en" catalog changes.

### CODE REVIEW

**Comment by stephdl** [comment]
Hi davidep

Thank for the PR

If I understand well I need to install something more to retrieve the remote translation, do you have some pointer ?

**Comment by stephdl** [comment]
It seems that I'm not a maintainer of this project

[build@buildrpm nethserver-ddclient]$ tx push -s
Pushing translations for resource nethserver.DdClient:
Pushing source file (root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_DdClient.php)
Exception: Only maintainers are allowed to update the source file.

Can I be granted or do I need my own session of transifex.....and what about for other modules ????

**Comment by stephdl** [comment]
now I pull all transifex file, spanish is translated, how I build my rpm ?
[build@buildrpm nethserver-ddclient]$ tx pull -a
New translations found for the following languages: ru_RU, el, nl, fr_FR, pt, de, tr, it, hu, es
Pulling new translations for resource nethserver.DdClient (source: root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_DdClient.php)
 -> ru_RU: .tx/nethserver.DdClient/ru_RU_translation
 -> el: .tx/nethserver.DdClient/el_translation
 -> nl: .tx/nethserver.DdClient/nl_translation
 -> fr_FR: .tx/nethserver.DdClient/fr_FR_translation
 -> pt: .tx/nethserver.DdClient/pt_translation
 -> de: .tx/nethserver.DdClient/de_translation
 -> tr: .tx/nethserver.DdClient/tr_translation
 -> it: .tx/nethserver.DdClient/it_translation
 -> hu: .tx/nethserver.DdClient/hu_translation
 -> es: .tx/nethserver.DdClient/es_translation
Done.

**Comment by DavidePrincipi** [comment]
Hi @stephdl 

I didn't address the Transifex permissions problem! Perhaps we can set up the auto-update URL
http://docs.transifex.com/faq/#can-i-update-source-files-automatically

What do you think?

About pulls: they happens on nethserver-lang repository only. We could set up a weekly procedure that pulls and rebuilds RPM langpacks automatically.

**Pull request merged**
